name: teknisi_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  chat_bubbles: ^1.3.1
  dio: ^5.2.0
  expandable_page_view: ^1.0.17
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  firebase_ui_auth: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^14.1.1
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  get_it: ^7.6.0
  google_maps_flutter: ^2.3.0
  hive: ^2.2.3
  image_picker: ^0.8.7+5
  intl: ^0.17.0
  json_annotation: ^4.8.1
  location: ^4.4.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0

dev_dependencies:
  freezed: ^2.3.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
